version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: syncorbisphp_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: OrbisAHOPHP
      MYSQL_USER: syncorbis
      MYSQL_PASSWORD: syncorbis123
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./docker/mysql/init:/docker-entrypoint-initdb.d
    command: --default-authentication-plugin=mysql_native_password
    networks:
      - syncorbis_network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: syncorbisphp_phpmyadmin
    restart: always
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: rootpassword
    ports:
      - "8080:80"
    depends_on:
      - mysql
    networks:
      - syncorbis_network

volumes:
  mysql_data:

networks:
  syncorbis_network:
    driver: bridge
